FROM ubuntu:16.04
MAINTAINER nerogit <nero.union12@gmail.com>

RUN apt-get update
RUN apt-get install -y software-properties-common vim git

RUN git clone https://github.com/nerogit/dotfiles.git
RUN cd dotfiles/ && ./setup.sh

RUN git clone https://github.com/pwndbg/pwndbg
RUN cd pwndbg && ./setup.sh

